module.exports = [
  {
    id: 'mba',
    name: 'Magic Bazar',
    address: '131 Avenue de France',
    zipcode: '75013',
    city: 'Paris',
    phone: '0971249887',
    link: 'https://www.magicbazar.fr',
  },
  {
    id: 'maj',
    name: 'Majestik',
    address: '148 Avenue du Maine',
    zipcode: '75014',
    city: 'Paris',
    phone: '0982479040',
    link: 'https://www.majestikgames.com',
  },
  {
    id: 'mco',
    name: 'Magic Corporation',
    address: '24 Boulevard Beaumarchais',
    zipcode: '75011',
    city: 'Paris',
    phone: '0954210725',
    link: 'http://www.magiccorporation.com',
  },
  {
    id: 'dra',
    name: 'Le Repaire du Dragon',
    address: '43 Avenue Simon Bolivar',
    zipcode: '75019',
    city: 'Paris',
    phone: '0144847069',
    link: 'http://www.lerepairedudragon.fr',
  },
  {
    id: 't2j',
    name: 'Troll 2 Jeux',
    address: "5-17 Place d'Aligre",
    zipcode: '75012',
    city: 'Paris',
    phone: '0143409046',
    link: 'https://www.troll2jeux.com',
  },
  {
    id: 'uch',
    name: 'Uchronies Games',
    address: '61 Rue Letellier',
    zipcode: '75015',
    city: 'Paris',
    phone: '0145798693',
    link: 'http://www.uchroniesgames.fr',
  },
  {
    id: 'lwt',
    name: 'La Waaagh Taverne',
    address: '16 rue de Stanislas',
    zipcode: '75006',
    city: 'Paris',
    phone: '0982241423',
    link: 'http://www.waaagh-taverne.fr',
  },
]
